### PR TITLE
Load sysconfig file in openntpd.service

### PR DESCRIPTION
**Pull request by ilyaevseev**

### CODE REVIEW

**Comment by poettler-ric** [comment]
Worked fine, thank you.

The only thing which is bothering me is that you have to rename the downloaded archives, but I don't have the time to change that, yet.

**Comment by ilyaevseev** [comment]
> The only thing which is bothering me is that you have to rename the downloaded archives

Archives are downloaded directly from releases on Github. I just keep their names unchanged.

**Comment by poettler-ric** [comment]
On my end it comes out as "openntpd-openbsd-openntpd-6.0p1.tar.gz" and "openntpd-portable-6.0p1.tar.gz"... Nevermind, it's not like there are releases every week. Thanks for the work you put in :) .

**Comment by poettler-ric** [comment]
My bad, I should have used curl and not chromium ;)

**Comment by ilyaevseev** [comment]
Macht alles richtig! :)

    rpmspec -P *.spec | awk '/^Source/ && /:\/\// { print "wget -cN", $2 }' | sh

**Pull request merged**
